# Generated by Django 5.0.3 on 2024-03-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBulkData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_to', models.CharField(choices=[('Country', 'Country'), ('State', 'State')], max_length=10)),
                ('filename', models.FileField(upload_to='uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
