# Generated by Django 5.0.3 on 2024-03-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addbulkdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbulkdata',
            name='upload_to',
            field=models.CharField(choices=[('Country', 'Country'), ('State', 'State'), ('Branch', 'Branch')], max_length=10),
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sales', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.state')),
            ],
        ),
    ]
