# Generated by Django 5.0.3 on 2024-04-01 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_addbulkdata_upload_to_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='date',
            field=models.DateTimeField(default='2001-01-01'),
        ),
        migrations.AddField(
            model_name='branches',
            name='date_enter',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
