# Generated by Django 5.0.3 on 2024-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_branches_date_branches_date_enter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='date',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
