# Generated by Django 5.0.3 on 2024-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_branches_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='date',
            field=models.DateTimeField(default='2001-01-01'),
        ),
    ]
